development:
  servie_url: 'https://lolcation-service.loldesign.com.br'
  token: ''
  sandbox: true
staging:
  servie_url: 'https://lolcation-service.loldesign.com.br'
  token: ''
  sandbox: true
production:
  servie_url: 'https://lolcation-service.loldesign.com.br'
  token: ''
